config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "landing#index"
  resources :users
  get "/projects", to: "projects#index"
  get "/projects/:user/:project_name", to: "projects#show", as: :project

  get "/info", to: "info#show"

  get "/dashboard", to: "landing#dashboard", as: :dashboard
  get "/leaderboards", to: "landing#leaderboards", as: :leaderboards

  resources :admin, only: [] do
    collection do
      get "/dashboard", to: "admin#dashboard", as: :dashboard
    end
  end

  # otp auth + session
  # resources :sessions

  post "/signin", to: "sessions#create", as: :signin
  get "/auth/code/:code", to: "sessions#exchange_code", as: :exchange_code
  post "/rsvp", to: "rsvps#create", as: :rsvp

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  ## prize shit
  resources :prizes do
    member do
      post :add_to_box
    end
  end

  resources :user_prizes, only: [] do
    member do
      patch :claim
    end
  end

  get "/prize_box", to: "users#prize_box", as: :prize_box

  get "/starter-projects", to: "launchpad#show"
  get "/getting-started", to: redirect("/getting-started/overview")
  get "/getting-started/:page", to: "overview#show", as: "overview_page"

  get "/advanced/:page", to: "advanced#show", as: "advanced_page"
  get "/advanced/", to: redirect("/advanced/overview")

  get "/guides/:page", to: "guides#show", as: "guides_page"
  get "/guides/", to: redirect("/guides/overview")

  get "/events", to: "events#index"

  get "/schedule", to: "schedule#index"
end

app/controllers/advanced_controller.rb
class AdvancedController < MarkdownController
end

app/views/advanced/_sidebar.html.erb
<div class="border-t-4 md:border-t-0 md:border-r-4 border-[#2E2A54] text-white h-full flex flex-col gap-4 justify-start mt-8 fixed">
  <div class="flex flex-col justify-start p-8">
    <div class="text-center grid grid-cols-1 gap-2 text-xl">
      <%# link_to "Projects", projects_path, class: "#{current_page?(projects_path) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 rounded transition duration-100 block" %>
      <%= link_to "Overview", advanced_page_path("overview"), class: "#{current_page?(advanced_page_path("overview")) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 px-6 rounded transition duration-100 block font-dystopian" %>
      <%= link_to "Project Guidelines", advanced_page_path("project-guidelines"), class: "#{current_page?(advanced_page_path("project-guidelines")) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 px-6 rounded transition duration-100 block font-dystopian" %>
      <%= link_to "Submitting", advanced_page_path("submitting"), class: "#{current_page?(advanced_page_path("submitting")) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 px-6 rounded transition duration-100 block font-dystopian" %>
      <%= link_to "Start your design", advanced_page_path("design-guide"), class: "#{current_page?(advanced_page_path("design-guide")) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 px-6 rounded transition duration-100 block font-dystopian" %>

      <p class="text-sm font-bold mt-6 text-left align-left">Extra info:</p>
      <%= link_to "Part Sourcing", advanced_page_path("part-sourcing"), class: "#{current_page?(advanced_page_path("part-sourcing")) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 px-6 rounded transition duration-100 block font-dystopian" %>
      <%= link_to "Resources & tips", advanced_page_path("resources"), class: "#{current_page?(advanced_page_path("resources")) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 px-6 rounded transition duration-100 block font-dystopian" %>
      <%= link_to "What is shipping?", advanced_page_path("shipping"), class: "#{current_page?(advanced_page_path("shipping")) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 rounded transition duration-100 block font-dystopian" %>
      <%= link_to "Project ideas", advanced_page_path("ideas"), class: "#{current_page?(advanced_page_path("ideas")) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 rounded transition duration-100 block font-dystopian" %>
      <%= link_to "Troubleshooting", advanced_page_path("troubleshooting"), class: "#{current_page?(advanced_page_path("troubleshooting")) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 rounded transition duration-100 block font-dystopian" %>
      <%# <%= link_to "Other communities", advanced_page_path("faq"), class: "#{current_page?(advanced_page_path("submit")) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 rounded transition duration-100 block font-dystopian" %>
    </div>
  </div>
</div>

app/views/advanced/show.html.erb
<div class="markdown-content font-poppins 2xl:max-w-6xl max-w-5xl md:mx-8 xl:ml-0 md:ml-16 mx-2">
    <%= raw @content %>
</div>