config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "landing#index"
  resources :users
  get "/projects", to: "projects#index"
  get "/projects/:user/:project_name", to: "projects#show", as: :project

  get "/info", to: "info#show"

  get "/dashboard", to: "landing#dashboard", as: :dashboard
  get "/leaderboards", to: "landing#leaderboards", as: :leaderboards

  resources :admin, only: [] do
    collection do
      get "/dashboard", to: "admin#dashboard", as: :dashboard
    end
  end

  # otp auth + session
  # resources :sessions

  post "/signin", to: "sessions#create", as: :signin
  get "/auth/code/:code", to: "sessions#exchange_code", as: :exchange_code
  post "/rsvp", to: "rsvps#create", as: :rsvp

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  ## prize shit
  resources :prizes do
    member do
      post :add_to_box
    end
  end

  resources :user_prizes, only: [] do
    member do
      patch :claim
    end
  end

  get "/prize_box", to: "users#prize_box", as: :prize_box

  get "/starter-projects", to: "launchpad#show"
  get "/getting-started", to: redirect("/getting-started/overview")
  get "/getting-started/:page", to: "overview#show", as: "overview_page"

  get "/advanced/:page", to: "advanced#show", as: "advanced_page"
  get "/advanced/", to: redirect("/advanced/overview")

  get "/guides/:page", to: "guides#show", as: "guides_page"
  get "/guides/", to: redirect("/guides/overview")

  get "/events", to: "events#index"

  get "/schedule", to: "schedule#index"
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/views/landing/_card.html.erb
<div class="bg-[#544FFF] rounded p-8 max-w-xl text-md text-center transition-transform duration-200 hover:scale-102">
  <p class="text-xl font-bold"><%= title %></p>
  <div class="mt-4 text-md">
    <p><%= content %></p>
  </div>
</div>

app/views/landing/_emailform.html.erb
<div class="flex flex-col gap-4">
    <%= form_with url: rsvp_path, method: :post do |form| %>
    <div class="border-4 border-[#544FFF] rounded flex items-center justify-center">
        <%= form.text_field :email, placeholder: "Enter your email to join!", class: "landing-input bg-white text-black px-4 py-2 w-3/4 md:w-[300px] flex-grow outline-none" %>
        <%= form.hidden_field :url_params, value: request.query_string %>
        <%= form.submit "→", class: "landing-button bg-[#544FFF] text-white px-4 py-2 font-bold" %>
    </div>
    <% end %>
    <% if flash[:notice] %>
        <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4" role="alert">
        <span class="block sm:inline"><%= flash[:notice] %></span>
        </div>
    <% end %>

    <% if flash[:alert] %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
        <span class="block sm:inline"><%= flash[:alert] %></span>
        </div>
    <% end %>

</div>

app/views/landing/_kit.html.erb
<div class="group h-[30rem] w-[24rem] 2xl:h-[32rem] 2xl:w-[28rem] [perspective:1000px] mx-auto">
  <div class="relative h-full w-full rounded shadow-xl transition-all duration-500 [transform-style:preserve-3d] group-hover:[transform:rotateY(180deg)]">
    <!-- front -->
    <div class="absolute inset-0 h-full w-full rounded bg-[#272239] border-4 border-[#544FFF] text-center [backface-visibility:hidden] flex flex-col justify-between">
      <div class="p-8">
        <% if badge.present? %>
          <p class="bg-[#544FFF] absolute -top-6 left-1/2 -translate-x-1/2 py-2 px-8 rounded-3xl font-bold"><%= badge %></p>
        <% end %>
        <div class="my-auto">
            <%= image_tag image, class: "w-32 h-32 mx-auto p-2" %>
            <p class="text-2xl font-bold mt-8"><%= title %></p>
            <p class="mt-2 text-sm"><%= description %></p>
        </div>
      </div>
      <div class="font-bold text-sm bottom-0 bg-[#544FFF] py-2 absolute w-full">
        <p>More info -></p>
      </div>
    </div>

    <!-- back -->
    <div class="absolute inset-0 h-full w-full rounded bg-[#544FFF] text-white text-center p-8 [transform:rotateY(180deg)] [backface-visibility:hidden]">
      <div class="flex flex-col h-full justify-center items-center">
        <p class="text-2xl font-bold"><%= title %></p>
        <p class="mt-4 text-sm"><%= back_description %></p>
        <p class="mt-4 text-md">Learn how to:</p>
        <ul class="list-disc list-inside mt-2 text-sm">
          <% learnings.each do |learning| %>
            <li><%= learning %></li>
          <% end %>
        </ul>
        <a href="<%= link %>" class="mt-6 bg-white text-[#544FFF] font-bold py-2 px-4 rounded-lg hover:bg-gray-200">Check it out!</a>
      </div>
    </div>
  </div>
</div>

app/views/landing/_kitsoon.html.erb
<div class="group h-[30rem] w-[24rem] 2xl:h-[32rem] 2xl:w-[28rem] mx-auto">
  <div class="relative h-full w-full rounded">
    <!-- front -->
    <div class="absolute inset-0 h-full w-full rounded bg-[#272239] border-4 hover:border-[#818181] border-[#585858] text-center [backface-visibility:hidden] flex flex-col justify-between transistion-colors duration-100">
      <div class="p-8">
        <% if badge.present? %>
          <p class="bg-[#544FFF] absolute -top-6 left-1/2 -translate-x-1/2 py-2 px-8 rounded-3xl"><%= badge %></p>
        <% end %>
        <div class="my-auto">
            <%= image_tag image, class: "w-32 h-32 mx-auto p-2" %>
            <p class="text-2xl font-bold mt-8"><%= title %></p>
            <p class="mt-2 text-sm"><%= description %></p>
        </div>
      </div>
      <div class="absolute w-full font-bold text-sm bottom-0 group-hover:bg-[#818181] bg-[#585858] py-2 text-white transition-colors duration-100">
        <p>COMING SOON</p>
      </div>
    </div>

  </div>
</div>

app/views/landing/_video.html.erb
<div class="relative mt-12">
  <%= image_tag "landing/landing4.png", style: "width: 100%;" %>
  <div class="absolute inset-0 flex justify-center items-center">
    <div class="bg-[#544FFF] md:p-80 md:py-48 p-4 rounded-lg text-white text-center">
      insert video here
    </div>
  </div>
</div>

app/views/landing/dashboard.html.erb
<h1>Dashboard</h1>

app/views/landing/leaderboards.html.erb
<h1>Leaderboard</h1>