config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "landing#index"
  resources :users
  get "/projects", to: "projects#index"
  get "/projects/:user/:project_name", to: "projects#show", as: :project

  get "/info", to: "info#show"

  get "/dashboard", to: "landing#dashboard", as: :dashboard
  get "/leaderboards", to: "landing#leaderboards", as: :leaderboards

  resources :admin, only: [] do
    collection do
      get "/dashboard", to: "admin#dashboard", as: :dashboard
    end
  end

  # otp auth + session
  # resources :sessions

  post "/signin", to: "sessions#create", as: :signin
  get "/auth/code/:code", to: "sessions#exchange_code", as: :exchange_code
  post "/rsvp", to: "rsvps#create", as: :rsvp

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  ## prize shit
  resources :prizes do
    member do
      post :add_to_box
    end
  end

  resources :user_prizes, only: [] do
    member do
      patch :claim
    end
  end

  get "/prize_box", to: "users#prize_box", as: :prize_box

  get "/starter-projects", to: "launchpad#show"
  get "/getting-started", to: redirect("/getting-started/overview")
  get "/getting-started/:page", to: "overview#show", as: "overview_page"

  get "/advanced/:page", to: "advanced#show", as: "advanced_page"
  get "/advanced/", to: redirect("/advanced/overview")

  get "/guides/:page", to: "guides#show", as: "guides_page"
  get "/guides/", to: redirect("/guides/overview")

  get "/events", to: "events#index"

  get "/schedule", to: "schedule#index"
end

app/views/shared/_audio.html.erb
<script>
      function toggleMute() {
      var myAudio = document.getElementById('background-audio');
      myAudio.muted = !myAudio.muted;
      var audioToggle = document.getElementById('audio-toggle');
      audioToggle.textContent = myAudio.muted ? '🔇' : '🔊';
    }
    </script>

    <div class="fixed bottom-0 right-0 z-50 p-4">
    <audio id="background-audio" loop autoplay muted data-turbo-permanent>
      <source src="/highwaymusic.mp3" type="audio/mpeg">
      Your browser does not support the audio element.
    </audio>

    <button id="audio-toggle" onclick="toggleMute()" class="bg-[#5453FF] rounded-full p-3 px-4 border-4 border-white text-white">
      🔇
    </button>
</div>

app/views/shared/_sidebar.html.erb
<div class="w-72 border-r-4 border-r-[#2E2A54] text-white h-screen fixed flex flex-col gap-4 justify-start">
  <div class="flex-grow flex flex-col justify-start p-5 mt-6">

    <div class="text-center grid grid-cols-1 gap-2 text-xl font-dystopian">
      <%= link_to "Projects", projects_path, class: "#{current_page?(projects_path) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 rounded transition duration-100 block" %>
    </div>

  </div>

  <% if current_user %>
    <%= link_to "@#{current_user.username}", user_path(current_user), class: "#{current_page?(user_path(current_user)) || current_page?(edit_user_path(current_user)) ? 'bg-[#564CAD]' : 'hover:bg-[#564CAD]'} bg-[#2E2A54] p-2 transition duration-100 block" %>
  <% end %>
</div>

app/views/shared/_topbar.html.erb
<div x-data="{ open: false }" class="w-full bg-[#302C61] text-white px-8 shadow-md fixed top-0 left-0 z-50">

  <div class="flex items-center justify-between md:justify-start">

    <div class="flex items-center space-x-4">
      <%= link_to root_path do %>
        <%= image_tag "/logo2.png", alt: "Logo", class: "max-h-[70px]" %>
      <% end %>
    </div>

    <!-- mobile (closed) -->
    <button @click="open = !open" class="md:hidden text-white focus:outline-none">
      <svg 
        xmlns="http://www.w3.org/2000/svg" 
        class="h-6 w-6 transform transition-transform duration-300" 
        :class="{ 'rotate-90': open }" 
        fill="none" 
        viewBox="0 0 24 24" 
        stroke="currentColor"
      >
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
      </svg>
    </button>

    <!-- desktop -->
    <div class="hidden md:flex items-center space-x-6 my-4 ml-8 *:font-dystopian *:uppercase *:hover:underline 2xl:text-2xl text-xl text-center text-[#AFBDEF]">
        <%= link_to "Getting started", "/getting-started", class: "#{request.path.start_with?('/getting-started') ? 'glow' : ''}" %>
        <%= link_to "Custom projects", "/advanced", class: "text-[#AFEFCB] #{request.path.start_with?('/advanced') ? 'glow' : ''}" %>
        <%= link_to "Guides", "/guides", class: "text-[#D1AFEF] #{request.path.start_with?('/guides') ? 'glow' : ''}" %>
        <%= link_to "Gallery", projects_path, class: "#{current_page?(projects_path) ? 'glow' : ''}" %>
        <%= link_to "Events", events_path, class: "#{current_page?(events_path) ? 'glow' : ''}" %>
        <%= link_to "Faq", "/getting-started/faq", class: "#{current_page?('/getting-started/faq') ? 'glow' : ''}" %>
    </div>

    <div class="hidden md:flex items-center ml-auto text-[#AFBDEF] text-xl font-bold">
        <a href="https://hackclub.com/" target="_blank" rel="noopenner noreferrer"><%= image_tag "/hcflag.svg", class: "max-h-[40px] ml-8 hover:-rotate-6 transition-transform duration-100" %></a>
    </div>
  </div>

  <!-- mobile (open) -->
  <div 
    x-show="open" 
    x-transition:enter="transition ease-out duration-100" 
    x-transition:enter-start="opacity-0 transform scale-95" 
    x-transition:enter-end="opacity-100 transform scale-100" 
    x-transition:leave="transition ease-out duration-100" 
    x-transition:leave-start="opacity-100 transform scale-100" 
    x-transition:leave-end="opacity-0 transform scale-95" 
    class="md:hidden mt-4 space-y-4 pb-5 *:font-dystopian *:uppercase *:hover:underline *:text-2xl flex flex-col"
  >
    <%= link_to "Getting started", "/getting-started" %>
    <%= link_to "Starter projects", "/starter-projects" %>
    <%= link_to "Custom projects", "/advanced" %>
    <%= link_to "Gallery", projects_path %>
    <%= link_to "Events", events_path %>
    <%= link_to "Faq", "/getting-started/faq" %>
  </div>
</div>